name: dcase2020_task2
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1e=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - pymongo=3.9.0=py37he6710b0_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - setuptools=46.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchaudio=0.4.0=py37
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.43.0=py_0
  - typing=3.6.4=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - audioread==2.1.8
    - cachetools==4.0.0
    - cffi==1.14.0
    - chardet==3.0.4
    - colorama==0.4.3
    - decorator==4.4.2
    - docopt==0.6.2
    - future==0.18.2
    - gitdb==4.0.2
    - gitpython==3.1.0
    - google-auth==1.11.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - idna==2.9
    - joblib==0.14.1
    - jsonpickle==1.3
    - librosa==0.7.2
    - llvmlite==0.31.0
    - markdown==3.2.1
    - munch==2.5.0
    - numba==0.48.0
    - oauthlib==3.1.0
    - packaging==20.3
    - protobuf==3.11.3
    - py-cpuinfo==5.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pytorch-lightning==0.7.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - rsa==4.0
    - sacred==0.8.1
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - smmap==3.0.1
    - soundfile==0.10.3.post1
    - tensorboard==2.1.1
    - urllib3==1.25.8
    - werkzeug==1.0.0
    - wrapt==1.12.1
prefix: /home/paul/miniconda3/envs/dcase2020_task2

